# Generated by Django 5.2.8 on 2025-11-16 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
    ]
