# Generated by Django 5.2.8 on 2025-11-16 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_invoice_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="currency",
            field=models.CharField(default="BST", max_length=10),
        ),
    ]
