# Generated by Django 5.2.8 on 2025-11-16 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_alter_invoice_currency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="invoice_type",
            field=models.CharField(
                choices=[
                    ("event", "Event Payment"),
                    ("membership", "Monthly Fee"),
                    ("registration_fee", "Registration Fee"),
                    ("recruitment_fee", "Recruitment Fee"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=20,
            ),
        ),
    ]
