# Generated by Django 5.2.8 on 2025-11-16 03:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("cover_image_url", models.URLField(blank=True, null=True)),
                ("start_at", models.DateTimeField()),
                ("end_at", models.DateTimeField()),
                ("is_online", models.BooleanField(default=False)),
                ("meeting_url", models.URLField(blank=True, null=True)),
                ("location", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("workshop", "Workshop"),
                            ("meeting", "Meeting"),
                            ("competition", "Competition"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=50,
                    ),
                ),
                ("capacity", models.PositiveIntegerField(default=0)),
                ("registration_deadline", models.DateTimeField(blank=True, null=True)),
                ("created_by", models.CharField(blank=True, max_length=255, null=True)),
                ("timezone", models.CharField(blank=True, max_length=50, null=True)),
                ("organizers", models.TextField(blank=True, null=True)),
                ("tags", models.TextField(blank=True, null=True)),
                ("prerequisites", models.TextField(blank=True, null=True)),
                ("requirements", models.TextField(blank=True, null=True)),
                ("speakers", models.TextField(blank=True, null=True)),
                ("schedule", models.TextField(blank=True, null=True)),
                ("resources", models.TextField(blank=True, null=True)),
                ("faqs", models.TextField(blank=True, null=True)),
                ("agenda", models.TextField(blank=True, null=True)),
                ("documents", models.TextField(blank=True, null=True)),
                ("rules", models.TextField(blank=True, null=True)),
                ("prizes", models.TextField(blank=True, null=True)),
                ("judges", models.TextField(blank=True, null=True)),
                ("sponsors", models.TextField(blank=True, null=True)),
                ("social_links", models.TextField(blank=True, null=True)),
                ("registration_url", models.URLField(blank=True, null=True)),
                ("recording_url", models.URLField(blank=True, null=True)),
                ("platform", models.CharField(blank=True, max_length=255, null=True)),
                ("difficulty", models.CharField(blank=True, max_length=50, null=True)),
                ("registration_fee", models.FloatField(default=0)),
                ("currency", models.CharField(default="USD", max_length=10)),
                ("prize_pool", models.FloatField(blank=True, null=True)),
                ("max_team_size", models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name="EventRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("team_name", models.CharField(blank=True, max_length=255, null=True)),
                ("team_members", models.TextField(blank=True, null=True)),
                ("registered_at", models.DateTimeField(auto_now_add=True)),
                ("payment_status", models.CharField(default="pending", max_length=50)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="events.event"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="event",
            name="participants",
            field=models.ManyToManyField(
                related_name="events",
                through="events.EventRegistration",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
