# Generated by Django 5.2.8 on 2025-11-16 03:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventRegistrationForNonMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="Contact Email"),
                ),
                (
                    "full_name",
                    models.CharField(max_length=255, verbose_name="Full Name"),
                ),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "organization",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("team_name", models.CharField(blank=True, max_length=255, null=True)),
                ("team_members", models.TextField(blank=True, null=True)),
                ("registered_at", models.DateTimeField(auto_now_add=True)),
                ("payment_status", models.CharField(default="pending", max_length=50)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="events.event"
                    ),
                ),
            ],
        ),
    ]
