# Generated by Django 5.2.8 on 2025-11-16 02:26

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "primary_role",
                    models.CharField(
                        choices=[
                            ("Member", "Member"),
                            ("President", "President"),
                            ("Vice President", "Vice President"),
                            ("General Secretary", "General Secretary"),
                            ("Joint General Secretary", "Joint General Secretary"),
                            ("Organisation Secretary", "Organisation Secretary"),
                            (
                                "Associate Organisation Secretary",
                                "Associate Organisation Secretary",
                            ),
                            ("Treasurer", "Treasurer"),
                            ("Associate Treasurer", "Associate Treasurer"),
                            (
                                "Events & Management Secretary",
                                "Events & Management Secretary",
                            ),
                            (
                                "Associate Events & Management Secretary",
                                "Associate Events & Management Secretary",
                            ),
                            ("Publicity Secretary", "Publicity Secretary"),
                            (
                                "Associate Publicity Secretary",
                                "Associate Publicity Secretary",
                            ),
                            ("Publications Secretary", "Publications Secretary"),
                            (
                                "Associate Publications Secretary",
                                "Associate Publications Secretary",
                            ),
                            ("Official Secretary", "Official Secretary"),
                            (
                                "Associate Official Secretary",
                                "Associate Official Secretary",
                            ),
                            ("Executive Member", "Executive Member"),
                        ],
                        default="Member",
                        max_length=100,
                    ),
                ),
                ("department", models.CharField(max_length=100)),
                ("batch", models.CharField(max_length=10)),
                ("session", models.CharField(max_length=20)),
                ("designation", models.CharField(max_length=255)),
                ("quote", models.CharField(max_length=200)),
                ("bio", models.TextField()),
                ("phone", models.CharField(max_length=20)),
                ("whatsapp", models.CharField(blank=True, max_length=20, null=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("webmail", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "facebook",
                    models.URLField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.URLValidator()],
                    ),
                ),
                (
                    "instagram",
                    models.URLField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.URLValidator()],
                    ),
                ),
                (
                    "linkedin",
                    models.URLField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.URLValidator()],
                    ),
                ),
                (
                    "github",
                    models.URLField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.URLValidator()],
                    ),
                ),
                (
                    "twitter",
                    models.URLField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.URLValidator()],
                    ),
                ),
                (
                    "website",
                    models.URLField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.URLValidator()],
                    ),
                ),
                (
                    "image",
                    models.URLField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.URLValidator()],
                    ),
                ),
                ("join_date", models.DateField()),
                ("term", models.CharField(max_length=20)),
                ("address", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="details",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Details",
                "verbose_name_plural": "User Details",
                "ordering": ["-join_date"],
            },
        ),
    ]
