# Generated by Django 5.2.8 on 2025-11-16 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Notice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
                ("publish_date", models.DateField()),
                ("last_updated", models.DateField(auto_now=True)),
                ("author", models.CharField(blank=True, max_length=255, null=True)),
                ("category", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("archived", "Archived"),
                        ],
                        default="active",
                        max_length=10,
                    ),
                ),
                ("views", models.PositiveIntegerField(default=0)),
                (
                    "attachments",
                    models.TextField(
                        blank=True,
                        help_text='Store attachments as JSON string: [{"name": "file.pdf", "url": "https://..."}]',
                        null=True,
                    ),
                ),
            ],
        ),
    ]
